##########################
#        ZeusChat        #
#  Made by: YourPalJake  #
#   configuration file   #
##########################
version: 1.0


chatchannels:
  enabled: true
  channels:
    staffchat:
      prefix: '@'
      format: '&4&lStaffChat &c%player% &8&l» &r'
      color: true
      permissions:
        readpermission: zeuschat.staffchat.read
        writepermission: zeuschat.staffchat.write
        colorpermission: zeuschat.staffchat.color
      command:
        #Requires the write permission
        name: 'staffchat'
        description: Staffchat command
        usage: '/staffchat <toggle|message>'
        aliases:
          - 'sv'